version: '3.9'
services:
  github-runner:
    build: .
    environment:
      - ACCESS_TOKEN=${GITHUB_CI_TOKEN}
      - REPO=${GITHUB_CI_REPO}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - buildx_cache:/home/docker/.docker/buildx


