apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  # Образ с Apache Spark 3.3.0. Можно подставить свою версию.
  image: bitnami/spark:3.3.0
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  # Пример из встроенных examples
  mainApplicationFile: local:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.3.0.jar
  sparkVersion: "3.3.0"
  # Для установки в cluster-режиме драйвера
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
