apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-mart
spec:
  serviceName: "data-mart"
  replicas: 1
  selector:
    matchLabels:
      app: data-mart
  template:
    metadata:
      labels:
        app: data-mart
    spec:
      containers:
      - name: data-mart
        image: daniinxorchenabo/data-mart-python-k8s:latest-dev-7
        env:
          - name: K8S_MONGO_USER
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_MONGO_USER
          - name: K8S_MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_MONGO_PASSWORD
          - name: K8S_MONGO_EXTERNAL_HOST
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_MONGO_EXTERNAL_HOST
          - name: K8S_MONGO_EXTERNAL_PORT
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_MONGO_EXTERNAL_PORT

          - name: K8S_SPARK_MASTER_URL
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_SPARK_MASTER_URL
          - name: K8S_SPARK_EXECUTOR_MEMORY
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_SPARK_EXECUTOR_MEMORY
          - name: K8S_SPARK_EXECUTOR_CORES
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_SPARK_EXECUTOR_CORES
          - name: K8S_SPARK_EXECUTOR_INSTANCES
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_SPARK_EXECUTOR_INSTANCES
          - name: K8S_SPARK_DRIVER_MEMORY
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_DATAMART_SPARK_DRIVER_HOST
          - name: K8S_SPARK_DRIVER_HOST
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_DATAMART_SPARK_DRIVER_HOST
          - name: K8S_SPARK_DRIVER_BIND_ADDRESS
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_SPARK_DRIVER_BIND_ADDRESS
          - name: K8S_SPARK_DRIVER_PORT
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_DATAMART_SPARK_DRIVER_PORT
          - name: K8S_SPARK_BLOCKMANAGER_PORT
            valueFrom:
              secretKeyRef:
                name: spark-cluster-secrets
                key: K8S_DATAMART_SPARK_BLOCKMANAGER_PORT
        ports:
        - containerPort: 12080
        - containerPort: 45555
        - containerPort: 45556
        - containerPort: 31555
        - containerPort: 31556

---
apiVersion: v1
kind: Service
metadata:
  name: data-mart
spec:
  selector:
    app: data-mart
  ports:
  - name: web-ui
    port: 12080
    targetPort: 12080
    nodePort: 31280
    protocol: TCP
  - name: driver-port
    port: 31555
    targetPort: 31555
    nodePort: 31555
  - name: block-manager-port
    port: 31556
    targetPort: 31556
    nodePort: 31556
  type: NodePort
