apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5-enterprise
        ports:
        - name: http
          containerPort: 7474
        - name: bolt
          containerPort: 7687
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password"
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-nodeport
  labels:
    app: neo4j
spec:
  type: NodePort
  selector:
    app: neo4j
  ports:
  - name: http
    port: 7474         # внутри кластера
    targetPort: 7474   # в контейнере
    nodePort: 30744    # внешний порт на узле
  - name: bolt
    port: 7687
    targetPort: 7687
    nodePort: 30787
