apiVersion: v1
kind: Service
metadata:
  name: kayvan-release-spark-master-svc
  labels:
    app.kubernetes.io/name: spark
    app.kubernetes.io/component: master
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: spark
    app.kubernetes.io/component: master
  ports:
    - name: web-ui
      port: 8080
      targetPort: 8080
      nodePort: 30080  # <-- порт на ноде
    - name: web-ui-2
      port: 30880
      targetPort: 30880
      nodePort: 30880  # <-- порт на ноде
    - name: web-ui-3
      port: 30881
      targetPort: 30881
      nodePort: 30881  # <-- порт на ноде
    - name: web-ui-4
      port: 30480
      targetPort: 30480
      nodePort: 30480  # <-- порт на ноде
    - name: spark
      port: 7077
      targetPort: 7077
      nodePort: 30077  # <-- ещё один порт на ноде
    - name: spark-2
      port: 30777
      targetPort: 30777
      nodePort: 30777  # <-- ещё один порт на ноде
    # добавь другие порты при необходимости
