version: '3.9'

services:
  producer:
    image: daniinxorchenabo/itmo-prod-dl-labs-env:lighting-cu121-dev-latest
    build:
      target: dev_build_cuda
      args:
        REQUIREMENTS_FILE: ${BUILD_BACKEND_REQUIREMENTS_FILE:-cu_12_2.txt}
    command: ./docker/before_learn.sh
    volumes:
      - type: bind
        source: ../docker/jupyter_config
        target: /root/.jupyter/
      - type: bind
        source: ..
        target: /workspace/NN