name: Continuous Delivery

on:
  workflow_dispatch:    # Позволяет запускать вручную
    inputs:
      deploy:
        description: 'Choose deploy environment'
        required: true
        default: 'staging'
  schedule:
    - cron: '0 0 1 * *'   # По расписанию
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed         # После завершения CI pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
  

    - name: Copy .env file
      run: |
        cp ./env/example.env ./env/.env
        echo "JUPYTER_TOKEN=${{ secrets.JUPYTER_TOKEN }}" >>  ./env/.env
        echo "AI_WEIGHTS_FILENAME=${{ secrets.AI_WEIGHTS_FILENAME }}" >>  ./env/.env
        echo "AI_WEIGHTS_REPO=${{ secrets.AI_WEIGHTS_REPO }}" >>  ./env/.env
        echo "AI_WEIGHTS_REPO_FILENAME=${{ secrets.AI_WEIGHTS_REPO_FILENAME }}" >>  ./env/.env
        cp ./env/.env ./env/unittests.env

    - name: Run tests
      run: |
        docker-compose -f ./docker/dev.docker-compose.yml -f ./docker/test.docker-compose.yml --env-file ./env/unittests.env  up  --no-deps unittests 


